#!/usr/bin/env node

import { program } from "commander";
import chalk from "chalk";
import { readFileSync } from "fs";
import { analyzeCommand } from "./commands/analyze.js";
import { applyCommand } from "./commands/apply.js";
import { statsCommand } from "./commands/stats.js";
import { readConfig } from "./utils/config.js";

const pkg = JSON.parse(
  readFileSync(new URL("../package.json", import.meta.url), "utf8"),
);

// Suppress the startup banner when only version info is requested
const versionRequested =
  process.argv.includes("-v") || process.argv.includes("--version");

if (!versionRequested) {
  console.log(
    chalk.bold.hex("#4a9eff")(`\n  git-shrink`) +
      chalk.dim(` v${pkg.version}`) +
      chalk.dim("  — semantic commit history compressor\n"),
  );
}

program
  .name("git-shrink")
  .version(pkg.version, "-v, --version", "output the current version")
  .description("Intelligently compresses bloated git histories");

program
  .command("analyze")
  .alias("a")
  .description("Analyze commits and suggest groupings")
  .option(
    "-n, --count <number>",
    "number of commits to analyze from HEAD",
    "50",
  )
  .option("-b, --branch <branch>", "branch to analyze", "HEAD")
  .option("--from <hash>", "analyze commits from this hash")
  .option("--to <hash>", "analyze commits to this hash", "HEAD")
  .option("--auto", "skip interactive mode, auto-select best groupings")
  .option("--dry-run", "show what would change without writing anything")
  .option("--min-group <number>", "minimum commits to form a group", "2")
  .option("--threshold <score>", "similarity score threshold (0-100)", "60")
  .action(async (opts) => {
    const config = await readConfig();
    await analyzeCommand({ ...config, ...opts });
  });

program
  .command("apply <rebase-file>")
  .alias("ap")
  .description("Apply a rebase script generated by analyze")
  .option("--dry-run", "validate the script without executing")
  .action(async (rebaseFile, opts) => {
    await applyCommand(rebaseFile, opts);
  });

program
  .command("stats")
  .alias("s")
  .description("Show commit health stats for this repository")
  .option("-n, --count <number>", "number of commits to include", "100")
  .action(async (opts) => {
    await statsCommand(opts);
  });

program.addHelpText(
  "after",
  `
${chalk.bold("Examples:")}
  ${chalk.cyan("git-shrink analyze")}                     Analyze last 50 commits interactively
  ${chalk.cyan("git-shrink analyze --count 100 --auto")}  Auto-group last 100 commits
  ${chalk.cyan("git-shrink analyze --dry-run")}           Preview groupings without writing
  ${chalk.cyan("git-shrink stats")}                       Show repository commit health score
  ${chalk.cyan("git-shrink apply rebase-plan.txt")}       Apply a saved rebase plan

${chalk.bold("Config:")}  Place a ${chalk.yellow(".gitshrinkrc")} or ${chalk.yellow("gitshrink")} key in package.json
`,
);

program.parse();
